	INSERT into bus values('RAJUS',	'POLLACHI',	NULL,'01:02' ,'01:04');
	INSERT into bus values('GOVT',	'POLLACHI',	NULL, '  01:10  ' ,'01:15');
INSERT into bus values	('GOVT',	'ODDANCHATRAM',	NULL, ' 01:20',	'01:25');
INSERT into bus values	('GOVT',	'OOTY',	NULL,' 01:25	  ' ,'       		01:30');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI','01:35','01:40');
INSERT into bus values	('GOVT',	'VALPARAI',	NULL,  '01:40 ', '01:45');
	INSERT into bus values('GOVT',	'POLLACHI',	NULL,'  01:45', ' 01:50');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI','01:50','01:55');
INSERT into bus values	('GOVT',	'SALEM',	NULL,'02:05	' ,'       	02:10');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI', '02:30','02:35');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL, '                  02:35	   ' ,'      		02:40');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                	02:40	    ', '     		02:45');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                   	02:50	 ', '        		02:55');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,	          '                      02:52'	,'          		02:55');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	                       '03:05',	'03:10');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',                     	'03:20',	'03:25');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',         	'03:30','03:35');
INSERT into bus values	('RAJUS',	'POLLACHI',	NULL,           '        	03:45	          	 ', '        			03:50');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,	          '          03:50		       	  ', '       	   	03:55');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	                '03:55'	,'04:00');
INSERT into bus values	('GOVT',	'METTUPALAYAM',	NULL,	          '      04:00		      	       ', '  	    	04:05');
INSERT into bus values	('GOVT',	'PALANI'	,NULL,           '            	04:05		    	  ' ,'       	      	04:10');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	            '04:20'	,'04:25');              
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	            '04:25'	,'04:30');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',     	    '04:35',	'04:40');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,	          '          04:45	          	'	,'04:50');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	                '04:50',	'04:55');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	                '04:55',	'05:00');
INSERT into bus values	('GOVT',	'KOTHAGIRI',	NULL,           '        	05:00'	,	          	'05:05');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	                  '05:10'	,	          '	05:15');
INSERT into bus values	('GOVT',	'TIRUPUR',	NULL,	          '                  05:00		  ', '       	05:15');
INSERT into bus values	('GOVT',	'TIRUPUR',	NULL,	          '              05:15	       ' ,'  		05:15');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	                '05:20'	,'05:25');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,	          '                  05:30	   ', '      		05:32');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	            '05:32'	,'05:35');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',             	'05:50',	'05:55');
INSERT into bus values	('RAJUS',	'COIMBATORE',	'POLLACHI',	            '05:54	',' 05:56');
INSERT into bus values	('SST',	'COIMBATORE',	'POLLACHI',                 	'05:55',	'05:5');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	            '05:55'	,'06:00');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	            '06:05',	'06:08');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	06:00	', '         		06:10');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	            '06:15',	'06:20');
INSERT into bus values	('KPK',	'POLLACHI',	NULL,           '                    	06:12	', '         		06:22');
INSERT into bus values	('GOVT',	'PALAKKAD',	NULL,           '                    	06:20	', '         		06:24');
INSERT into bus values	('SRK',	'COIMBATORE',	'POLLACHI',	                    '06:25',	'06:26');
INSERT into bus values	('PRIVATE',	'COIMBATORE',	'POLLACHI',	        '06:20'	,'06:30');
INSERT into bus values	('SRT',	'COIMBATORE',	'POLLACHI',     	'06:25'	,'06:35');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	06:35	',	'          	06:40');
INSERT into bus values	('MRT',	'COIMBATORE',	'POLLACHI',	'06:35',	'06:45');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'06:45',	'06:47');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'06:50',	'06:55');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	06:50	' ,'         		06:55');
INSERT into bus values	('MBS',	'POLLACHI',	NULL,           '                    	06:50	',	'          	07:00');
INSERT into bus values	('GOVT',	'PALAKKAD',	NULL,           '                    	07:00	' ,'         		07:02');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'07:00',	'07:05');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'07:05',	'07:10');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'07:10',     '07:15');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'07:15',	'07:20');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'07:20',	'07:25');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	07:25	' ,'         		07:30');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	07:30	', '         		07:35');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	07:35	', '         		07:40');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'07:40',	'07:45');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'07:45',	'07:50');
INSERT into bus values	('GOVT',	'OOTY',	NULL,           '                    	07:50	' ,'         		07:52');
INSERT into bus values	('PKM',	'COIMBATORE',	'POLLACHI',	'07:40'	,'07:56');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'07:55',	'08:00');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'08:00',	'08:05');
INSERT into bus values	('GOVT',	'METTUPALAYAM',	NULL,           '                    	08:08	' ,'         		08:12');
INSERT into bus values	('THIRUMOORTHI',	'POLLACHI',	NULL,           '                    	08:10	', '         		08:15');
	INSERT into bus values('KBS',	'POLLACHI',	NULL,           '                    	08:16	' ,'         		08:17');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	08:20	', '         		08:22');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'08:22',	'08:25');
INSERT into bus values	('KPK',	'POLLACHI',	NULL,           '                    	08:20	', '         		08:27');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'08:25',	'08:30');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'08:30'	,'08:35');
INSERT into bus values	('MBS',	'POLLACHI',	NULL,'08:25	',' 	08:30');
INSERT into bus values	('CHITRA',	'POLLACHI',	NULL,           '                    	08:35	' ,'         		08:47');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'08:45','08:50');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'08:38	','08:52');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	08:50	' ,'         		08:55');
INSERT into bus values	('KAMALAM',	'COIMBATORE',	'POLLACHI',	'08:55	','08:57');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	08:57	' ,'         		09:00');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'09:00	','09:10');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'09:05','	09:10');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	09:10	' ,'         		09:11');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	09:10	' ,'         		09:14');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	09:14	' ,'         		09:16');
INSERT into bus values	('PRIVATE',	'COIMBATORE',	'POLLACHI',	'08:47','09:18');
	INSERT into bus values('GOVT',	'POLLACHI',	NULL,           '                    	09:15	', '         		09:20');
INSERT into bus values	('GOVT',	'METTUPALAYAM',	NULL,           '                    	09:20	', '         		09:25');
INSERT into bus values	('AMMAN',	'COIMBATORE',	'POLLACHI',	'09:27','	09:30');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	09:25	' ,'         		09:30');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'09:35','	09:37');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'09:40','	09:43');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	09:45	' ,'         		09:50');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	09:50	' ,'         		09:52');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'09:20	','09:55');
INSERT into bus values	('SKT',	'POLLACHI',	NULL,           '                    	09:55	',	'          	09:57');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'09:55','	10:00');
INSERT into bus values	('SMMS',	'POLLACHI',	NULL,           '                    	10:00	'	,'          	10:02');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'10:00','	10:03');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'10:05','	10:10');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'10:10	','10:18');
INSERT into bus values	('MBS',	'POLLACHI',	NULL,           '                    	10:10	' ,'         		10:18');
INSERT into bus values	('SRN',	'POLLACHI',	NULL,           '                    	10:18	' ,'         		10:20');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'10:20','	10:22');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'10:05','	10:25');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'10:25','	10:30');
INSERT into bus values	('GOVT',	'METTUPALAYAM',	NULL,           '                    	10:30	',	'          	10:35');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	10:35	' ,'         		10:37');
INSERT into bus values	('RAJUS',	'POLLACHI',	NULL,           '                    	10:35	' ,'         		10:40');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'10:40','	10:44');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'10:45','	10:48');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'10:40','	10:52');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'10:52','	10:54');
INSERT into bus values	('SST',	'POLLACHI',	NULL,           '                    	10:45	'	,'          	10:55');
INSERT into bus values	('LAKSHMI',	'POLLACHI',	NULL,           '                    	10:55	', '         		11:00');
INSERT into bus values	('MRT',	'COIMBATORE',	'POLLACHI',	'10:50','	11:02');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	11:00	', '         		11:03');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	11:02	' ,'         		11:06');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'11:05','	11:10');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	11:10	' ,'         		11:15');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'11:15','	11:16');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	11:15	',	'          	11:20');
INSERT into bus values	('SRT',	'POLLACHI',	NULL,           '                    	11:10	' ,'         		11:22');
	INSERT into bus values('GOVT',	'POLLACHI',	NULL,           '                    	11:15	', '         		11:23');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'11:20','	11:25');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'11:25','	11:28');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'11:28','	11:30');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'11:30','	11:35');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	11:35	' ,'         		11:40');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'11:40','	11:42');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	11:40	' ,'         		11:45');
INSERT into bus values	('KBS',	'POLLACHI',	NULL,           '                    	11:47	' ,'         		11:48');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'11:50','	11:55');
INSERT into bus values	('JAISAKTHI',	'COIMBATORE',	'POLLACHI','11:20','	11:58');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	11:55	', '         		12:01');
INSERT into bus values	('KRK',	'POLLACHI',	NULL,           '                    	11:55	' ,'         		12:03');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'12:00','	12:05');
INSERT into bus values	('RAJUS',	'COIMBATORE',	'POLLACHI',	'12:05','	12:07');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'12:05','	12:10');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	12:10	', '         		12:15');
INSERT into bus values	('MBS',	'POLLACHI',	NULL,           '                    	12:00	' ,'         		12:18');
INSERT into bus values	('SRK',	'COIMBATORE',	'POLLACHI',	'12:18','	12:20');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'12:20','	12:25');
INSERT into bus values	('PKM',	'COIMBATORE',	'POLLACHI',	'11:50','	12:26');
INSERT into bus values	('GOVT',	'METTUPALAYAM',	NULL,           '                    	12:26	' ,'         		12:28');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	12:25	',	'          	12:30');
INSERT into bus values	('SST',	'COIMBATORE',	'POLLACHI',	'12:30','	12:32');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	12:15	' ,'         		12:38');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'12:35','	12:40');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	12:40	', '         		12:42');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'12:20','	12:43');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'12:45	','12:52');
INSERT into bus values	('GOVT',	'METTUPALAYAM',	NULL,           '                    	12:55	', '         		13:02');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	13:00	', '         		13:05');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	13:05	',	'          	13:10');
INSERT into bus values	('CHITRA', 	'POLLACHI',	NULL,           '                    	13:10	' ,'         	13:12');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'13:10','	13:15');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'13:15','	13:20');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'13:20','	13:25');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'13:25','	13:30');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	13:30	' ,'         	13:35');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'13:35','	13:40');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'13:40	','13:47');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'13:45','	13:50');
INSERT into bus values	('GOVT',	'GURUVAYOUR',	NULL,           '                    	05:58 ', '        		06:02');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	13:45 ' ,'        		13:55');
INSERT into bus values	('GOVT',	'METTUPALAYAM',	NULL,           '                    	13:50	', '         	13:55');
INSERT into bus values	('KPK',	'POLLACHI',	NULL,           '                    	13:50 ' ,'        		14:00');
INSERT into bus values	('GOVT',	'METTUPALAYAM',	NULL,           '                    	14:00 ', '        		14:02');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'14:00','	14:05');
INSERT into bus values	('GKT',	'POLLACHI',	NULL,           '                    	14:05 ', '        		14:07');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'14:05','	14:10');
INSERT into bus values	('SRN',	'POLLACHI',	NULL,           '                    	14:10 ' ,'        		14:12');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	14:10 ', '        		14:15');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'14:10','	14:15');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	14:15 ' ,'        		14:20');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'14:10','	14:22');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'14:20','	14:25');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'14:25','	14:25');
INSERT into bus values	('RNS',	'POLLACHI',	NULL,           '                    	14:28 ' ,'        		14:30');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	14:30	', '         	14:32');
INSERT into bus values	('PRIVATE',	'COIMBATORE',	'POLLACHI',	'14:35','	14:37');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	14:40 ' ,'        		14:42');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	14:45 ' ,'        		14:50');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'14:50','	14:55');
INSERT into bus values	('RAJUS',	'POLLACHI',	NULL,           '                    	14:55 ' ,'        		14:56');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	14:55 ' ,'        		14:57');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	14:58 ' ,'        		15:00');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	15:00	', '         	15:02');
INSERT into bus values	('MBS',	'POLLACHI',	NULL,           '                    	14:30 ' ,'        		15:04');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'15:02','	15:07');
INSERT into bus values	('MRT',	'COIMBATORE',	'POLLACHI',	'14:50','	15:09');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	15:10 ', '        		15:12');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	15:10 ' ,'        		15:15');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	15:15 ', '        		15:16');
INSERT into bus values	('PRIVATE',	'COIMBATORE',	'POLLACHI',	'15:16','	15:19');
INSERT into bus values	('GOVT',	'PALLAKKAD',	NULL,           '                    	15:15 ', '        		15:20');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'15:20','	15:22');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'15:25','	15:27');
INSERT into bus values	('SRT',	'COIMBATORE',	'POLLACHI',	'15:20','	15:30');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	15:25 ', '        		15:33');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	15:30 ' ,'        		15:38');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'15:35','	15:40');
INSERT into bus values	('LAKSHMI',	'POLLACHI',	NULL,           '                    	15:40	', '         	15:44');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	15:44	' ,'         	15:48');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'15:48','	15:52');
INSERT into bus values	('KBS',	'POLLACHI',	NULL,           '                    	15:52 ', '        		15:55');
INSERT into bus values	('GOVT',	'VALPARAI',	NULL,           '                    	15:55 ', '        		16:00');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'16:00','	16:05      ');    	
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'16:05	','16:07');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'16:07','	16:12');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'16:15','	16:16');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'16:16','	16:20');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'16:20','	16:25');
INSERT into bus values	('PRIVATE',	'COIMBATORE',	'POLLACHI',	'16:25	','16:30');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'16:30','	16:32');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	16:32 ' ,'        		16:37');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'16:35','	16:40');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'16:40','	16:43');
INSERT into bus values	('GOVT',	'KOTHAGIRI',	NULL,           '                    	16:42 ' ,'        		16:45');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'16:40','	16:47');
INSERT into bus values	('SST',	'POLLACHI',	NULL,           '                    	16:35 ', '        		16:50');
INSERT into bus values	('GOVT',	'METTUPALAYAM',	NULL,           '                    	16:50	', '         	16:55');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'16:50','	17:00');
INSERT into bus values	('GOVT',	'OOTY',	NULL,           '                    	17:00 ' ,'        		17:02');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	17:00	', '         	17:03');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	17:02	' ,'         	17:06');
INSERT into bus values	('PRIVATE',	'POLLACHI',	NULL,           '                    	16:20 ' ,'        		17:10');
INSERT into bus values	('CHITHRA',	'POLLACHI',	NULL,           '                    	17:10 ' ,'        		17:15');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'17:16','17:20');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	17:20 ' ,'        		17:22');
INSERT into bus values('GOVT',	'COIMBATORE',	'POLLACHI',	'17:20','	17:25          	');
INSERT into bus values	('MBS',	'POLLACHI',	NULL,           '                    	17:15	' ,'         	17:27');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'17:25','	17:30');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'17:30','	17:35');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'17:35','	17:40');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'17:40','	17:42');
INSERT into bus values	('PKM',	'COIMBATORE',	'POLLACHI',	'17:15','	17:45');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI','17:45','	17:47');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	17:45	', '         	17:50');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'17:50','	17:52');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	17:45	' ,'         	17:50');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'17:50	','17:52');
INSERT into bus values	('KPK',	'POLLACHI',	NULL,           '                    	17:30	', '         	17:53');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	17:50	', '         	17:55');
INSERT into bus values	('SRN',	'POLLACHI',	NULL,           '                    	17:55	' ,'         	17:58');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'18:00','	18:05');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'18:05','	18:08');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	18:08 ', '        		18:10');
INSERT into bus values	('GOVT',	'METTUPALAYAM',	NULL,           '                    	18:10 ', '        		18:12');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	18:12 ' ,'        		18:14');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	18:13 ' ,'        		18:15');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	18:15 ' ,'        		18:24');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'18:24','18:26');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	18:28 ' ,'        		18:30');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'18:30','	18:32');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	18:28 ' ,'        		18:30');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'18:30','18:32');
INSERT into bus values	('GKT',	'POLLACHI',	NULL,           '                    	18:30	' ,'         	18:35');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'18:35','	18:42');
INSERT into bus values	('SRK',	'COIMBATORE',	'POLLACHI',	'18:45','18:46');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'18:45','18:50');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	18:55 ', '        		18:56');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'18:55','19:00');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	19:00 ', '        		19:03');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'19:00','	19:05');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'19:05','	19:08');
INSERT into bus values	('RAJUS',	'COIMBATORE',	'POLLACHI',	'19:05','	19:10');
INSERT into bus values	('RNS',	'POLLACHI',	NULL,           '                    	19:10	' ,'         	19:12');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	19:05	', '         	19:18');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'18:50','	19:20          	');
INSERT into bus values	('SST',	'POLLACHI',	NULL,           '                    	19:20	' ,'         	19:23');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	19:23	', '         	19:25');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	19:25	', '         	19:30');
INSERT into bus values	('GOVT',	'METTUPALAYAM',	NULL,           '                    	19:20	' ,'         	19:35');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'19:35','	19:40');
INSERT into bus values	('RAJUS',	'POLLACHI',	NULL,           '                    	19:42 ', '        		19:43');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	19:40 ' ,'        		19:45');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'19:45','	19:50');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	19:50 ' ,'        		19:52');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'19:50','	19:55');
INSERT into bus values	('MBS',	'POLLACHI',	NULL,           '                    	19:25 ' ,'        		19:57');
INSERT into bus values	('KBS',	'POLLACHI',	NULL,           '                    	19:55 ' ,'        		20:00');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'19:30','	20:05');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'20:05','	20:10');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'20:10','	20:15');
INSERT into bus values	('KPK',	'POLLACHI',	NULL,           '                    	20:00	', '         	20:16');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	20:15 ', '        		20:20');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	20:20	', '         	20:25');
INSERT into bus values	('GOVT',	'METTUPALAYAM',	NULL,           '                    	20:25 ', '        		20:30');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	20:30 ', '        		20:35');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'20:35','	20:40');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'20:40','	20:45');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'20:45','	20:50');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	20:50 ' ,'        		20:55');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'20:55','	21:00');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'20:55','	21:05');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'20:55','	21:05');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	21:05	', '         	21:10');
INSERT into bus values	('CHITHRA',	'POLLACHI',	NULL,           '                    	21:10 ' ,'        		21:12');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	21:10	', '         	21:15');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'21:15','	21:20');
INSERT into bus values	('SST',	'POLLACHI',	NULL,           '                    	21:20 ' ,'        		21:22');
INSERT into bus values('GOVT',	'COIMBATORE',	'POLLACHI',	'21:20','	21:25');
INSERT into bus values	('PRIVATE',	'COIMBATORE',	'POLLACHI',	'21:25','	21:32');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	21:32 ', '        		21:35');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI','21:35','	21:40');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	21:40 ' ,'         	21:45');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'21:45','	21:50');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	21:52 ' ,'         	21:57');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	22:00 ' ,'         	22:05');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'22:05','	22:10   ');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	22:10	', '               22:15');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	22:15	' ,'               22:20');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'22:20','	22:25');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	22:25 ' ,'                 	22:30');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	22:30	', '               22:35');
INSERT into bus values	('SRN',	'POLLACHI',	NULL,           '                    	22:35	' ,'                   22:40');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'22:40','	22:45');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	22:55	', '                   23:00');
INSERT into bus values	('GKT',	'POLLACHI',	NULL,           '                    	23:05	' ,'                       23:10');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	23:10	', '                   23:15');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'23:15','	23:20');
INSERT into bus values	('RNS',	'POLLACHI',	NULL,           ' 23:25 ', '                 	23:30');
INSERT into bus values	('RAJUS',	'POLLACHI',	NULL,           '                    	23:35 ', '             	23:40');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'23:45','	23:50');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'00:00	','00:05');
INSERT into bus values	('GOVT',	'POLLACHI',	NULL,           '                    	00:05	', '                     00:10');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'00:25','	00:30');
INSERT into bus values	('KBS',	'POLLACHI',	NULL,    '00:35	', '                        00:40');
INSERT into bus values	('GOVT',	'COIMBATORE',	'POLLACHI',	'00:50','00:55');
